### ISSUE TITLE
Indicating exposure and outcome variables with ggdag_adjustment_set()

### ISSUE THREAD

**Issue by ianmoran11** [malcolmbarrett/ggdag#10]
Hi Malcolm,

Thank you for putting this package together. I'm finding it very useful. 

Just wondering whether you've considered indicating which variables are the exposure or outcome in the plot produced by ggdag_adjustment_set().

Here's an example of what this might look like using a chart from the readme: 
![image](https://user-images.githubusercontent.com/11229116/58383208-40b94e80-8017-11e9-8457-65705b7e495f.png)

If you're interested, the changes behind this are here: https://github.com/ianmoran11/ggdag/commit/dfa86bbef83ce1f7bf5e4c20fa3c78656dfa0808

Cheers,
Ian

**Comment by tjohnson250** [comment]
Despite the dual coding with both shape and color, I think the use of four discrete colors doesn't really work visually. Perhaps using purple for all unadjusted nodes, keep the blue edge between exposure and outcome, and use triangles as above for exposure and outcome. Another idea might be to use a muted color for the adjusted variables so that they are less salient, a normal valued color for unadjusted, and brighter colors for the exposure and outcome nodes and edge. In other words, a stepped gradient color scheme with 3 steps. Here is one such blue gradient suggested by colorbrewer as colorblind and photocopy friendly: #deebf7 #9ecae1 #3182bd

**Comment by malcolmbarrett** [comment]
Hi @ianmoran11; apologies, I missed this. I agree with @tjohnson250 that the coding is hard to understand here. My suggestion would be to use the underlying `dag_adjustment_sets()` and `node_status()` functions to add these variables to the tibble, then plot them yourself with the underlying geoms (take a look at the vignettes or the source code for `ggdag_adjustment_set()`; I have intentionally made most of these fast plot functions wrappers around dag/data and geom functions). That way you can have exactly the aesthetics you want.

I would also suggest that you instead code adjustment as shape and color as status to keep those channels separate.
