### ISSUE TITLE
Default ggdag theme

### ISSUE THREAD

**Issue by NickCH-K** [malcolmbarrett/ggdag#28]
Is there a reason that the default theme in recent releases has switched from `theme_dag()` (or `theme_dag_blank()` or `theme_void()`, I'm actually not sure what it was using) to the default `ggplot` theme? Having a void background seems to make a lot more sense for a `ggdag`. Is there a plan to change this back in the next CRAN release? I'm using **ggdag** 0.2.1 now.

Mostly I'm going to teach a bunch of people how to use **ggdag** in a few weeks and I'm trying to figure out if I also need to teach them how to use `ggplot` themes.

Thank you!

**Comment by malcolmbarrett** [comment]
Hey, thanks for your interest. I've quite liked your work visualizing causal inference and am happy to hear you're using ggdag for teaching.

I can give you a definitive answer: no, this will not be changing. From here on out, ggdag will use the same themeing and scales as ggplot2 unless absolutely necessary. If you're teaching ggdag outside of the context of ggplot2, my recommendation would just to teach students to do something like this:

```r
library(ggdag)
theme_set(theme_dag())
```

You know your students and class needs better than me, of course, but in my experience, students grasp themes very easily, and with this code you won't need to add it with `+`.

I wrestled with this decision for a long time, but I am now very confident that this is the right design approach. I made several opinionated design choices in the initial release, and some got in the way of ggplot2's incredible customization system. It's always been possible to change ggdag how you like (since fundamentally it's just ggplot2) but some of those initial choices made it harder to get there. 

That was the single greatest mistake I made in designing this package. The reason is that no default theme or color palette will suit the needs of everyone. A minimal theme without axes works for many, perhaps most, DAGs, but one can absolutely imagine situations where grids and axes have meaning to communicate. Moreover, there are many, many ways to do minimal themes; ggdag alone has 4 options, and base ggplot2 has several more. 

Hard-coding themes and scales, as I did in the initial release, made it harder to customize ggdag. The code above doesn't work with ggdag 0.1.0 because the theme function called locally in ggdag functions would trump `theme_set()`. Changing scales and colors would generate warnings because those functions set them locally, and they needed to be overridden. 

So, while it's true that there are aspects of those old defaults that made life a little easier, they were secretly hinderances. I learned that the hard way when I got sick of the default theme ggdag originally had! Anyway, if you like, there's also some guidance at the end of this blog post for using the old look: https://malco.io/2019/09/17/tidy-causal-dags-with-ggdag-0-2-0/
