### ISSUE TITLE
tidy_dagitty(..., layout = "dendrogram") is broken

### ISSUE THREAD

**Issue by coreyyanofsky** [malcolmbarrett/ggdag#57]
The function `tidy_dagitty` contains these two lines:
```
layout_info <- dplyr::select(ggraph_layout, -x, -y) %>% 
  dplyr::mutate(name = as.character(name))
names(layout_info) <- c("name", ".ggraph.orig_index", "circular", 
  ".ggraph.index")
```
These lines assume that (excluding `x`, `y`) the `name` column will be first in the `ggraph_layout` tibble. For `layout = dendrogram` this assumption is violated: the first column is a logical vector named `leaf`, which gets renamed to `name`. (Later on there is a join on `name` that barfs due to type mismatch.)

**Comment by malcolmbarrett** [comment]
This is a #wontfix for me. Denodgrams are complex layout types, and it doesn't seem worth the effort to try to support them in ggdag since they're not as useful for this type of structure. I'd recommend working with ggraph directly if you have a pressing use case.

If this is an important feature to you, though, I'm open to a PR to better support them.
