### ISSUE TITLE
Moderator variables

### ISSUE THREAD

**Issue by variani** [malcolmbarrett/ggdag#6]
Thanks for the package! It has very nice plots, and I wish to use it to draw diagrams of causal relationships.

I couldn't find any option to introduce a moderator variable. Do you think there is any way to do this?

Figure 1 in this [article (pdf)](http://citeseerx.ist.psu.edu/viewdoc/download?doi=10.1.1.169.4836&rep=rep1&type=pdf) shows a decomposition of the moderator model, but I'd like to have a different diagram:

![](https://i0.wp.com/www.theanalysisfactor.com/wp-content/uploads/2018/12/var_rel6.png?ssl=1)

**Comment by malcolmbarrett** [comment]
Unfortunately, there's not an agreed upon way to show effect modification/moderation/interaction. I haven't been convinced that any are particularly better than the others, so it's not implemented. Part of the issue is that, according to Judea Pearl, effects are assumed to be heterogeneous by default in causal models.

Anyway, you can make the graph you shared relatively easily by tricking ggdag into thinking there is a node in the middle of the arrow from `x` to `y`, so all is not lost. There is also an alternative way of showing interaction using potential outcomes here: https://gist.github.com/malcolmbarrett/6604f357e06181b8cf421b3c68b78130 

``` r
library(ggdag)
library(tidyverse)

coords <- tribble(
  ~name,    ~x,  ~y,
  "x",      1,   1,
  "y",      2,   1,
  "m",      1.5, 0,
  "holder", 1.5, 1.05
)

dagify(
  y ~ x,
  holder ~ m,
  coords = coords
) %>% 
  ggplot(aes(x = x, y = y, xend = xend, yend = yend)) + 
    geom_dag_point(data = function(x) filter(x, name != "holder")) +
    geom_dag_edges() + 
    geom_dag_text(data = function(x) filter(x, name != "holder")) +
    theme_dag()
```

![](https://i.imgur.com/Bis5JC3.png)

**Comment by variani** [comment]
The trick with the holder node will work for me. Thanks for your quick reply!
