### ISSUE TITLE
`ggdag_equivalent_class` reversable edge error?

### ISSUE THREAD

**Issue by tjohnson250** [malcolmbarrett/ggdag#8]
In the code below, the CPDAG from `plot(equivalenceClass(gobs))` shows undirected (reversible) edges among all three variables, which I believe is correct. The CPDAG from `ggdag_equivalent_class(gobs)` shows an unreversible edge from E to C. This is using Version 0.1.0

```r
library(ggdag)
library(dagitty)

gobs <- dagitty('dag{
  A [pos="1,1"]
  E [pos="0,0"]
  C [pos="2,0"]
  A -> C A->E  E->C }')

plot(equivalenceClass(gobs))
ggdag_equivalent_class(gobs)
```

**Comment by malcolmbarrett** [comment]
Thank you for filing this!

This is happening because`equivalenceClass()` evidently returns a differently ordered DAG than `gobs`. For any edge that is reversible, it returns a pair where the start node and end node are decided by alphabetical order rather than their positions in the original DAG. For instance, if I change `A` to `Z`, it fails to recognize the other two instead. 

@jtextor, I can fix this on my end to recognize this behavior, but I thought you might want to think about it. While the start and end nodes are indeed arbitrary, to me using their user-specified ordering in the original DAG makes more sense. There are probably not many other cases where this matters, but something to think about. If you don't want to modify that, I'll deal with this here.

**Comment by tjohnson250** [comment]
This example shows the opposite problem. In the original DAG, X0 -> X3 <- X1 is an unshielded collider. `plot(equivalenceClass(gyp))` retains the directed edge, X0 -> X3, whereas `ggdag_equivalent_class(gyp)` shows it as undirected.

```{r}
library(ggdag)
library(dagitty)

gyp <- dagitty('dag{
    X0 [pos="0,1"]
    X1 [pos="0,2"]
    X2 [pos="0,0"]
    X3 [pos="1,1"]
    X4 [pos="2,1"]
    X1 -> X3 -> X4
    X2 -> X3
    X0 -> X3
    X0 -> X2
}')
plot(equivalenceClass(gyp))
ggdag_equivalent_class(gyp)
```

**Comment by malcolmbarrett** [comment]
Evidently, I was tired when I made this function. That's a separate bug fixed in #9. I'll keep this open to address the first one as well

**Comment by jtextor** [comment]
Hey Malcolm, in dagitty, graphs do not have an ordering of the variables. Indeed the order in which variables are iterated over is completely arbitrary. This is consistent with the standard mathematical understanding of graphs, where we define the vertices as a set (as opposed to a list).  I therefore wouldn't want any dagitty function to depend on the order in which vertices are given. 

A separate question is whether the original syntax used by the user to construct the graph should somehow be retained in the object, that is currently not the case.

**Comment by malcolmbarrett** [comment]
Sorry, I was a little unclear: by "order", I mean 1) the literal order of the edge syntax ("A -- B" vs "B -- A") and, consequently, the order in `edges(dag)`, which is in the first column and which is in the second. dagitty seems to put these node pairs in alphabetical order when an edge is reversible (not the entire DAG).

**Comment by jtextor** [comment]
OK, I understand it now. I indeed have a convention that for symmetric edges, the endpoints are ordered alphabetically. In fact there should be no semantic difference between A -- B and B -- A so it would probably be best to just check for both, but ordering them in this way speeds up the detection of symmetric edges inside my library (it goes up from O( n ) to O( 1 ), where n is the number of nodes). If I were to change that, I would also have to change the code that checks for edges, and this would make the whole package slower. I understand that it's annoying in this specific case and seems a surprising thing to do, but I at least wanted to explain that there's a reason for it. 

The real solution for this problem would be to provide a different function that directly calls the actual "getEdge()" method in the library, instead of first exporting the edges as strings and then checking for the strings. But that also in turn would require to actually store the underlying object in the R object, and I never found a good way to do that since R doesn't seem to have proper destructors ..

**Comment by malcolmbarrett** [comment]
Oops, I missed this @jtextor; thanks for the response. I'll handle it on my side, then!

**Comment by malcolmbarrett** [comment]
@tjohnson250 I believe both of these issues are fixed now. Thanks for filing them!
